# Variables
@baseUrl = http://localhost:3333

# Health check
GET {{baseUrl}}/health

###

# Get rooms
GET {{baseUrl}}/rooms

###

# Create room
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
  "name": "Test Room",
  "description": "This is a test room"
}